### ISSUE TITLE
Please re-publish 0.2.2 as 0.3.0

### ISSUE THREAD

**Issue by achingbrain** [ipfs/js-datastore-pubsub#20]
#19 changed how pubsub subscriptions are [listed](https://github.com/ipfs/js-datastore-pubsub/blob/master/src/index.js#L95) from:

```javascript
const subscriptions = await this._pubsub.ls()
```

to

```javascript
const subscriptions = await this._pubsub.getTopics()
```

This in effect forces the user to upgrade to a newer version of whatever `libp2p-pubsub` subclass they are using but also arrives as a stealth upgrade if your `package.json` contains `^0.2.1` as the version for this module.

This is not a backwards compatible change so should not be a patch release.

Please revert #19, republish v0.2.1 as v0.2.3, then reapply #19 and publish it as 0.3.0.

**Comment by vasco-santos** [comment]
hey @achingbrain 

apparently my release alias got broken from my laptop change. will have a look now at this. Thanks for reporting it

**Comment by vasco-santos** [comment]
everything is now released properly

**Comment by achingbrain** [comment]
Thanks!
